# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 04:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_webhooks', '0002_webhook_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackevent',
            name='event_payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
