# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 04:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield_compat.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trello_webhooks', '0003_auto_20170410_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackevent',
            name='event_payload',
            field=jsonfield_compat.fields.JSONField(default=dict),
        ),
    ]
